### ISSUE TITLE
Suggestions on how to host an app written with wish

### ISSUE THREAD

**Issue by bring-shrubbery** [charmbracelet/wish#73]
## The problem

I want to deploy the app to my domain so that it's accessible from the terminal via `ssh antoni.ai`, but I have some difficulties figuring out how to do it properly.

First, my go-to easy hosting provider (Railway) doesn't let ssh protocol through, so I can't deploy there. I've considered just getting a compute service like a droplet on digital ocean, but I also need to ssh into it to control it, so I can't expose port 22 there.

My best guess here is to just have a service running and listening on a different port, and then use a reverse proxy to point port 22 to the previously mentioned service, but I once again hit the issue of having the 22nd port occupied for controlling the service.

I also don't want to use my raspberry pi for this, because I don't want people ssh'ing into my home network, even if it looks pretty safe behind the TUI.

Any suggestions would be greatly appreciated! ❤️

**Comment by aymanbagabas** [comment]
Hi @bring-shrubbery!

I've been there before, having multiple SSH services (OpenSSH, and Wish) running on the same server is pretty common.

I'd suggest getting a computing service and running OpenSSH on a different port than your Wish application. You could reserve port `2222` for SSH access and port `22` for Wish, then forward all other traffic to your hosting provider, in this case, Railway. This way you would be able to access your Wish application using `ssh antoni.ai` since it runs on the default SSH port and access the computing service through port `2222` with `ssh -p2222 antoni.ai`.

I hope this helps :)

**Comment by bring-shrubbery** [comment]
Hey @aymanbagabas

Thanks a lot for the suggestion! I think this will work perfectly, I kinda ignored in my head the option of changing the default ssh port, but this completely makes sense!
